### PR TITLE
clean up color generators.

### PR DESCRIPTION
**Pull request by tjmahr**
`rgb_color()` was not generating rgb vectors. `hex_color()` could not generate "#000000"

### CODE REVIEW

**Comment by tjmahr** [comment]
Hmmm, I didn't check that `ch_rgb_color()`. That needs to be tweaked. What should `ch_rbg_color` (1) return? A 3-length vector of R, G and B? or a string?

**Comment by sckott** [comment]
maybe `replicate(10, x$rgb_color(), simplify = FALSE)`

**Comment by sckott** [comment]
@tjmahr does my above suggestion sound good? or something else?

**Comment by tjmahr** [comment]
All right, I dropped that change in. Let's see how it builds.

**Comment by sckott** [comment]
i think we just need to change the test now https://github.com/ropenscilabs/charlatan/blob/master/tests/testthat/test-fraudster.R#L22 given changed output

**Comment by sckott** [comment]
perfect, good build now. thanks @tjmahr

**Pull request merged**
